### ISSUE TITLE
dont allow special characters in usernames

### ISSUE THREAD

**Issue by CodeMyst** [CodeMyst/pastemyst-v2#138]

**Comment by Dmunch04** [comment]
has this been done?

**Comment by CodeMyst** [comment]
nope, didn't even start on this one.

**Comment by Dmunch04** [comment]
if you haven't planned on working on this yet, could i do it? im very bored lately and looking for stuff to do

**Comment by CodeMyst** [comment]
yeah of course. i guess i should explain this better then.

basically id like it so that users can only have usernames with alphanumerics and numbers. and this should get checked when creating the user: (https://github.com/CodeMyst/pastemyst-v2/blob/master/source/pastemyst/web/login.d#L192, https://github.com/CodeMyst/pastemyst-v2/blob/master/public/scripts/pages/createUser.js) and in the settings page: (https://github.com/CodeMyst/pastemyst-v2/blob/master/source/pastemyst/web/user.d#L77, https://github.com/CodeMyst/pastemyst-v2/blob/master/public/scripts/pages/settings.js)

**Comment by Dmunch04** [comment]
okay. i'll take a look

**Comment by CodeMyst** [comment]
oh could you also allow: - and _
