### ISSUE TITLE
Suggestions: Easter Egg, advert section, UI Animations, Full screen support, /api error, Other suggestion

### ISSUE THREAD

**Issue by anf** [CodeMyst/pastemyst-v2#174]
Please do it for me 🤣. An easter egg would be amazing, though no one would use it, but it would be fun 😄
An advert section in the settings menu that enables ads.
Animations while clicking UIs, not super detailed but just enough to make it feel like so
The code editor looks small, at least on my device, there should be a feature to max it out manually while writing code (idk, I write code and text there xD)
When I go to: https://paste.myst.rs/api-docs and click "/api". It gives me 404 not found, don't forget to fix that in version 2 😉
The: "a simple website for sharing code. version 1.7.2 (changelog)" could be changed to "A simple website for sharing code. version 1.7.2 (changelog)". May be it would look better..
When a user creates his/her first paste you can give a side bar (like dell and hp's site does) that asks for suggestions.

**Comment by CodeMyst** [comment]
who says there aren't already easter eggs on the site?

won't add ads ever.

i won't add any animations, its simpler without them.

a full width editor button is already added.

on pastemyst all text is "stylized" in a way that all letters are lower case.

the github link is always in the navigation so people can open issues for feedback.

**Comment by Dmunch04** [comment]
Personally I find most of these not necessary. Like fx the use of animations. I like the simplistic look and feeling of the site, and animations usually tend to ruin that. I also don't really get the advert section? Like do you mean to have ads on the page? And I don't really understand the 2 last points.

*(I'm just curious and wanted to give my opinion)*

**Comment by anf** [comment]
Yes, burn me everyone. Burn me, more more.. :kekw:

> who says there aren't already easter eggs on the site?
> There are? Please tell me xD
> won't add ads ever.
> rip, I give up
> i won't add any animations, its simpler without them.
> I can't argue with that.
> a full width editor button is already added.
> Nice, thanks :D
> on pastemyst all text is "stylized" in a way that all letters are lower case.
> Oh, rip
> the github link is always in the navigation so people can open issues for feedback.
Hm.. ok

> Personally I find most of these not necessary. Like fx the use of animations. I like the simplistic look and feeling of the site, and animations usually tend to ruin that. I also don't really get the advert section? Like do you mean to have ads on the page? And I don't really understand the 2 last points.
> Yes, they are not. But you have to agree that they look good. And ads, well why not xD.
> _(I'm just curious and wanted to give my opinion)_
> Thanks for the opinion. Your feedback has improved my way of response :D

Nope no need to reply xD. Case closed, I wish there was at least one good suggestion though :(..

**Comment by CodeMyst** [comment]
if i'd reveal all the easter eggs they wouldnt be secrets anymore :p

**Comment by nt314p** [comment]
I mean it is open source?

**Comment by CodeMyst** [comment]
doesn't mean i can't have easter eggs not in the repo but in the DB as pastes :p
