### ISSUE TITLE
weird text selection

### ISSUE THREAD

**Issue by Dmunch04** [CodeMyst/pastemyst-v2#220]
text selection is acting weird some places, like fx here
![image](https://user-images.githubusercontent.com/30357821/93713358-95ad9c00-fb5b-11ea-979f-6301d111a796.png)

paste id is `z0ny1gc5` for testing

**Comment by harshhh-dev** [comment]
What exactly did you do which caused this?

**Comment by Dmunch04** [comment]
paste the text and select it? exactly as shown above

**Comment by CodeMyst** [comment]
can't manage to reproduce it reliably, it happens rarely but still does happen.
