### ISSUE TITLE
<Bug> outlines on chrome.

### ISSUE THREAD

**Issue by haaarshsingh** [CodeMyst/pastemyst-v2#221]
Adds a weird and ugly outline when you click on the "paste title"

Seems to be a chrome only issue which is not present on Firefox

![image](https://user-images.githubusercontent.com/69592270/94860340-ed71c000-0403-11eb-9756-79286e4f5690.png)

**Comment by haaarshsingh** [comment]
I've fixed this in my fork of the project.

**Comment by CodeMyst** [comment]
could you create a PR for this then?

**Comment by haaarshsingh** [comment]
Sure. I was going to originally do it with my responsive navbar update, but I'll do it when I have time as you wish.
