### ISSUE TITLE
[maybe] real time multi user editing

### ISSUE THREAD

**Issue by CodeMyst** [CodeMyst/pastemyst-v2#29]
suggestion by muro

**Comment by Dmunch04** [comment]
WebRTC is an option (P2P). A good library for such, could be https://peerjs.com/

**Comment by CodeMyst** [comment]
Maybe even add error checking and autocomplete for some languages?

**Comment by Dmunch04** [comment]
Yeah that would be very cool. For auto-completion, something like <https://codemirror.net/demo/complete.html> could be used as demo?

**Comment by Dmunch04** [comment]
Perhaps something that could also be added sometime, could be a simple chat, so you can easily communicate while editing

**Comment by CodeMyst** [comment]
too much work would be needed for this, pastemyst shouldn't try to do everything.
