### ISSUE TITLE
add 1 month and 1 year expires in

### ISSUE THREAD

**Issue by CodeMyst** [CodeMyst/pastemyst-v2#32]

**Comment by CodeMyst** [comment]
For now, expired pastes still aren't implemented completely (pastes dont get actually deleted), but for now its enough to just add those 2 values to this enum: https://github.com/CodeMyst/pastemyst-v2/blob/master/source/pastemyst/data/expires.d

**Comment by Dmunch04** [comment]
Should be added in #41
