### ISSUE TITLE
Validate the language (just like the expiresIn value is validated)

### ISSUE THREAD

**Issue by CodeMyst** [CodeMyst/pastemyst-v2#34]

**Comment by CodeMyst** [comment]
Here's how `expiresIn` is being validated: https://github.com/CodeMyst/pastemyst-v2/blob/master/source/pastemyst/rest/paste.d#L60

What could be done is get the `languages.json` data file and check if the language name exists in the file.

**Comment by Dmunch04** [comment]
Added in #42
