### ISSUE TITLE
viewing raw pastes

### ISSUE THREAD

**Issue by CodeMyst** [CodeMyst/pastemyst-v2#39]
when visiting `/raw/:id/:pastyIndex` it should just show the plain text paste (like the github view raw feature) for the specified paste id and pasty index (since pastes can be consisted of more than 1 pasty). maybe show the paste and pasty title in the web page title.

**Comment by Dmunch04** [comment]
Added in #46

**Comment by Dmunch04** [comment]
Added in #46
