### ISSUE TITLE
link gitlab and github accounts

### ISSUE THREAD

**Issue by CodeMyst** [CodeMyst/pastemyst-v2#56]
if a person logs in with both gitlab and github should they be 2 separate accounts or the same account based on their email?

**Comment by Dmunch04** [comment]
Same account I suppose. That way you can link GitHub to an existing account created with GitLab, and vice versa. That's at least how I thought it would work.

**Comment by CodeMyst** [comment]
yeah i will probably do it that way, need to think about more stuff though.

in github and i think gitlab you can change your email, an account can have more than one email attached to it. a lot of edge cases to consider.

**Comment by CodeMyst** [comment]
you should be able to link a github account with a gitlab one and the other way around, a user will have field for the github and gitlab id, when linking the data from both accounts (if exists) will be merged.
