### ISSUE TITLE
show the number of pastes

### ISSUE THREAD

**Issue by CodeMyst** [CodeMyst/pastemyst-v2#6]

**Comment by CodeMyst** [comment]
pretty simple, just add a function in `db/db.d` to get number of pastes which should run [`db.collection.count`](https://docs.mongodb.com/manual/reference/method/db.collection.count/) and add that to `footer.dt`. unfortunately this function will need to be manually called before every `render` and passed to it, maybe there's a way for it to be automatically called?

**Comment by Dmunch04** [comment]
Should be added in #41
