### ISSUE TITLE
encryption of pastes

### ISSUE THREAD

**Issue by CodeMyst** [CodeMyst/pastemyst-v2#80]
i want the private pastes to be completely end-to-end encrypted, so that even with db access you can't see the contents of the pastes.

the problem is that for encryption i need a private key from a user, but the reigstration/login is done without passwords, so there is no key only the user knows about.

**Comment by Dmunch04** [comment]
Generate a random key when creating a private paste, and the user holds on to that? or is that not what you had in mind? more like something so the user doesnt have to do anything perhaps?

**Comment by CodeMyst** [comment]
yeah, wanted it to be more seamless, without having to input a password every time you create/view a paste.

a possibility would be to ditch oauth2 and use normal username/password accounts.

another possiblity is to look into oauth2 vs openid, since from what i currently know, oauth is not meant for authentication but for being able to get data from a service on behalf of the user, and openid is for authentication... will look more into that.

**Comment by CodeMyst** [comment]
what about keeping current oauth login, but if you want to make private pastes you will have to add a password to your account?

if youre a user that doesn't need private pastes, you have simple login with no passwords, but if you want to create secure private pastes youll have to also provide a password on login, and that password will be used only for encrypting pastes

**Comment by CodeMyst** [comment]
okay after a lot of thinking i think i will go with this approach.

private and encrypted pastes are separate. encrypted pastes will require a password to create and open. if no password is provided it will generate a random string as a password and it will send it to the user.

**Comment by CodeMyst** [comment]
also show that a paste is encrypted on the profile page with a small icon
