### ISSUE TITLE
show the paste language on the profile pages

### ISSUE THREAD

**Issue by CodeMyst** [CodeMyst/pastemyst-v2#99]

**Comment by Dmunch04** [comment]
What do you mean with 'overall'?

**Comment by CodeMyst** [comment]
nothing really, just made the issue so i dont forget. i like the idea of using the github style language bar, so we could do that one.

**Comment by Dmunch04** [comment]
Oh okay I see. I started on something similar. But instead it was just displaying the most average used language. But with intention to make a bar-like display
